import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const kumbh_Sans = Kumbh_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "InfoTech - IT Solutions & Technology Next.js Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kumbh_Sans.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
